version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: suppstore-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # This variable comes from the .env file written by the workflow
      MYSQL_DATABASE: supplements_db
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql

  backend:
    image: ahmhi003/suppstore-backend:${IMAGE_TAG:-latest}
    container_name: suppstore-backend
    restart: always
    depends_on:
      - database

  frontend:
    image: ahmhi003/suppstore-frontend:${IMAGE_TAG:-latest}
    container_name: app-frontend-1
    restart: always

  nginx-proxy:
    image: nginx:alpine
    container_name: app-nginx-proxy-1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend

volumes:
  db-data: