version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: suppstore-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supplements_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql

  backend:
    build: ./store
    container_name: suppstore-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/supplements_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database

  frontend:
    build: ./angular-frontend
    container_name: suppstore-frontend
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db-data: