USE supplementsdb;

INSERT INTO supplement (id, description, name, price, category, goal, discount, discount_percentage, price_after_discount) VALUES
(1, 'Supports immune function', 'Vitamin C', 19.99, 'Vitamins & Minerals', 'Health & Wellbeing', 'Yes', 10.00, 17.99),
(2, 'Helps muscle growth and recovery', 'Protein Powder', 39.99, 'Sports Nutrition', 'Build Muscle', 'No', NULL, NULL),
(3, 'Boosts energy and strength', 'Creatine', 29.99, 'Creatine', 'Endurance', 'No', NULL, NULL),
(4, 'Supports bone health and immune function', 'Vitamin D3', 14.99, 'Vitamins & Minerals', 'Health & Wellbeing', 'No', NULL, NULL),
(5, 'Enhances blood flow and pump during workouts', 'Pre-Workout Xtreme', 34.99, 'Pre-Workout', 'Endurance', 'Yes', 15.00, 29.74),
(6, 'High-protein vegan formula for muscle growth', 'Vegan Protein', 42.50, 'Vegan', 'Build Muscle', 'Yes', 20.00, 34.00),
(7, 'Helps fat metabolism and boosts energy', 'L-Carnitine', 24.99, 'Weight Loss', 'Weight Loss', 'No', NULL, NULL),
(8, 'Promotes joint health and flexibility', 'Omega-3 Fish Oil', 18.99, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(9, 'Boosts stamina and improves training output', 'Beta-Alanine', 22.99, 'Sports Nutrition', 'Endurance', 'Yes', 10.00, 20.69),
(10, 'Daily multivitamin for overall wellness', 'Multivitamin Complex', 16.75, 'Vitamins & Minerals', 'Health & Wellbeing', 'No', NULL, NULL),
(11, 'Rich in BCAAs for muscle recovery', 'BCAA Blast', 31.00, 'Sports Nutrition', 'Build Muscle', 'No', NULL, NULL),
(12, 'Supports healthy digestion and gut health', 'Probiotic Blend', 19.95, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(13, 'Reduces fatigue and improves endurance', 'Citrulline Malate', 27.00, 'Pre-Workout', 'Endurance', 'No', NULL, NULL),
(14, 'Natural appetite suppressant', 'Garcinia Cambogia', 21.99, 'Weight Loss', 'Weight Loss', 'Yes', 15.00, 18.69),
(15, 'Plant-based recovery formula', 'Vegan Recovery Shake', 39.99, 'Vegan', 'Endurance', 'No', NULL, NULL),
(16, 'Enhances brain function and focus', 'Ginkgo Biloba', 15.99, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(17, 'Protein bar for quick post-workout fuel', 'Whey Protein Bar', 3.50, 'Foods', 'Build Muscle', 'Yes', 5.00, 3.32),
(18, 'Essential minerals for athletes', 'Zinc & Magnesium', 13.75, 'Vitamins & Minerals', 'Health & Wellbeing', 'No', NULL, NULL),
(19, 'Caffeine-free pre-workout booster', 'Pump Surge', 33.00, 'Pre-Workout', 'Endurance', 'Yes', 10.00, 29.70),
(20, 'Green superfood blend for energy and detox', 'Supergreens Powder', 29.95, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(21, 'Essential amino acids for full recovery', 'EAA Matrix', 26.49, 'Sports Nutrition', 'Build Muscle', 'No', NULL, NULL),
(22, 'Natural fat burner with green tea', 'Thermogenic Burn', 28.99, 'Weight Loss', 'Weight Loss', 'No', NULL, NULL),
(23, 'Plant-based omega source', 'Flaxseed Oil Capsules', 17.00, 'Vegan', 'Health & Wellbeing', 'Yes', 10.00, 15.30),
(24, 'High-quality whey isolate for muscle recovery', 'Whey Isolate 90', 44.99, 'Sports Nutrition', 'Build Muscle', 'Yes', 25.00, 33.74),
(25, 'Plant-based BCAA for vegan athletes', 'Vegan BCAA Pro', 32.50, 'Vegan', 'Endurance', 'No', NULL, NULL),
(26, 'Appetite control with natural fiber', 'Glucomannan Capsules', 19.99, 'Weight Loss', 'Weight Loss', 'No', NULL, NULL),
(27, 'Anti-inflammatory support from turmeric', 'Turmeric Curcumin', 18.50, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(28, 'Carbohydrate drink for bulking phase', 'Mass Gainer XL', 49.99, 'Sports Nutrition', 'Build Muscle', 'No', NULL, NULL),
(29, 'Keeps your supplements fresh and organized', 'Supplement Storage Box', 9.99, 'Accessories', 'Health & Wellbeing', 'No', NULL, NULL),
(30, 'Hydration and electrolyte balance during training', 'Electrolyte Tabs', 12.99, 'Sports Nutrition', 'Endurance', 'No', NULL, NULL),
(31, 'Boost metabolism and support thyroid', 'Kelp Iodine Capsules', 14.99, 'Vitamins & Minerals', 'Health & Wellbeing', 'No', NULL, NULL),
(32, 'Natural pre-workout with green coffee & beetroot', 'Plant Power Pre', 31.99, 'Pre-Workout', 'Endurance', 'No', NULL, NULL),
(33, 'Delicious high-protein vegan snack', 'Vegan Protein Cookie', 2.99, 'Foods', 'Eat Vegan', 'No', NULL, NULL),
(34, 'Heavy-duty gym shaker for on-the-go drinks', 'Stainless Steel Shaker', 14.50, 'Accessories', 'Build Muscle', 'Yes', 10.00, 13.05),
(35, 'Supports lean muscle and energy levels', 'CLA Softgels', 23.00, 'Weight Loss', 'Weight Loss', 'No', NULL, NULL),
(36, 'Post-workout formula for rapid recovery', 'Recovery Matrix', 36.00, 'Sports Nutrition', 'Build Muscle', 'No', NULL, NULL),
(37, 'Boost natural testosterone and strength', 'Tribulus Terrestris', 26.99, 'Sports Nutrition', 'Build Muscle', 'No', NULL, NULL),
(38, 'Organic superfood powder for detox and energy', 'Spirulina Chlorella Mix', 22.50, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(39, 'Coconut water-based hydration drink', 'HydraCoco Sport', 3.99, 'Foods', 'Endurance', 'No', NULL, NULL),
(40, 'Low-carb protein snack for weight control', 'Protein Chips', 2.75, 'Foods', 'Weight Loss', 'No', NULL, NULL),
(41, 'Essential support for athletes’ heart health', 'CoQ10 Softgels', 20.49, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(42, 'Daily greens in capsule form', 'Green Blend Capsules', 17.95, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(43, 'High-caffeine fat burner with synephrine', 'Extreme Cut Thermo', 34.99, 'Weight Loss', 'Weight Loss', 'No', NULL, NULL),
(44, 'Natural antioxidant that supports cellular health', 'Resveratrol Capsules', 21.99, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(45, 'Vegan-friendly source of Omega-3s', 'Algae Oil Capsules', 19.99, 'Vegan', 'Eat Vegan', 'No', NULL, NULL),
(46, 'Provides daily calcium for bone strength', 'Calcium Citrate', 14.50, 'Vitamins & Minerals', 'Health & Wellbeing', 'No', NULL, NULL),
(47, 'Keeps protein fresh and easy to carry', 'Protein Powder Storage Container', 7.99, 'Accessories', 'Health & Wellbeing', 'No', NULL, NULL),
(48, 'All-natural energy bar with nuts and seeds', 'Natural Energy Bar', 2.49, 'Foods', 'Endurance', 'No', NULL, NULL),
(49, 'Aids relaxation and restful sleep', 'Magnesium Glycinate', 16.25, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(50, 'Non-dairy probiotic for gut balance', 'Vegan Probiotic', 18.00, 'Vegan', 'Eat Vegan', 'No', NULL, NULL),
(51, 'Enzyme blend to improve digestion', 'Digestive Enzymes Complex', 17.75, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(52, 'Collagen support for skin, hair, and nails', 'Marine Collagen Peptides', 28.50, 'Health & Wellbeing', 'Health & Wellbeing', 'Yes', 20.00, 22.80),
(53, 'Electrolyte-rich drink for hydration', 'Coconut Electrolyte Drink', 3.25, 'Foods', 'Endurance', 'No', NULL, NULL),
(54, 'Convenient all-in-one meal replacement shake', 'Vegan Meal Shake', 39.99, 'Vegan', 'Eat Vegan', 'No', NULL, NULL),
(55, 'Supports brain health and mood', 'L-Theanine Capsules', 15.99, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(56, 'Organic whole food multivitamin', 'Whole Food Multi', 29.99, 'Vitamins & Minerals', 'Health & Wellbeing', 'Yes', 15.00, 25.49),
(57, 'Daily greens smoothie mix', 'Green Superfood Blend', 26.50, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(58, 'Strengthens bones and immune system', 'Vitamin K2 + D3', 19.00, 'Vitamins & Minerals', 'Health & Wellbeing', 'No', NULL, NULL),
(59, 'Stainless steel pill organizer for travel', 'Pill Organizer Pro', 11.50, 'Accessories', 'Health & Wellbeing', 'No', NULL, NULL),
(60, 'Pure plant-based iron supplement', 'Vegan Iron Complex', 17.25, 'Vegan', 'Eat Vegan', 'No', NULL, NULL),
(61, 'Natural blend for hormone balance', 'Ashwagandha Root Extract', 21.75, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL),
(62, 'Whole grain high-fiber energy snack', 'Oat Protein Cookie', 3.00, 'Foods', 'Endurance', 'No', NULL, NULL),
(63, 'Supports immunity and stress reduction', 'Elderberry Gummies', 13.99, 'Health & Wellbeing', 'Health & Wellbeing', 'No', NULL, NULL);
